Feat/write question
taeo-sprint16/frontend pull request #10
Opened 2023-10-21 17:54 UTC by HA-SEUNG-JEONG

## 관련 문서

## 변경사항:

- 질문 작성 페이지에서 키워드 클릭 시 해당 키워드에 대한 placeholder가 변경됩니다.

<img width="219" alt="image" src="https://github.com/taeo-sprint16/frontend/assets/88266129/93d30c44-bb94-4796-b3a3-f50b8ff7a77e">
<img width="227" alt="image" src="https://github.com/taeo-sprint16/frontend/assets/88266129/e464b1d8-4050-41b3-9364-0fad878491be">

- textarea 내 텍스트 길이에 따라 height가 조정됩니다.

<img width="227" alt="image" src="https://github.com/taeo-sprint16/frontend/assets/88266129/9eb7f5c7-b66f-4e30-8741-d724f2ac6fa7">

<img width="255" alt="image" src="https://github.com/taeo-sprint16/frontend/assets/88266129/6f8d2fac-6382-41d9-a1d6-8cbcbc4955eb">

- 닉네임 입력 여부에 따라 버튼 비활성화/활성화
#### 닉네임 입력시
![image](https://github.com/taeo-sprint16/frontend/assets/88266129/b64b3aed-b32d-4a49-b5c5-061020b9b57e)

#### 닉네임 미입력시 
![image](https://github.com/taeo-sprint16/frontend/assets/88266129/a39291ec-5cf5-42b6-a62e-0ac2d614715b)

## 확인할 목록:

- 선택된 키워드가 placeholder에 잘 반영되는지?
-  textarea 텍스트 길이에 따라 height가 잘 조정되는지?
- 닉네임 입력여부에 따라 버튼 비활성화 및 활성화가 잘 되는지?

2023-10-22 03:04 UTC, bbung95 commented on src/components/NickName.tsx
>  const StyledQuestionContainer = styled.div`
<img width="331" alt="스크린샷 2023-10-22 오후 12 00 50" src="https://github.com/taeo-sprint16/frontend/assets/77668478/ad043239-cbe4-4eea-9dbd-67bd6135f2af">

align-items : center 로 되어 있어서 중간으로 정렬되는거 같아요! 수정이 필요할거 같습니다!

또 height값이 고정으로 812px이 되어 있는데 100vh? 변경하면 좋을거 같습니다!
웹으로 접근시에 화면이 짤려서 나오는 이슈가 있습니다ㅠ

2023-10-22 03:06 UTC, bbung95 commented on src/components/WriteQuestion.tsx
> +      <CompleteButton disabled={question === '' ? true : false}>
container wdith가 375px로 설정되어 있는데 버튼도 375px로 고정되어 있어서 조정이 필요할거 같아요

<img width="264" alt="스크린샷 2023-10-22 오후 12 06 23" src="https://github.com/taeo-sprint16/frontend/assets/77668478/3632372a-b864-4a87-b978-03424ddfeefd">

2023-10-22 03:09 UTC, bbung95 commented on src/components/WriteQuestion.tsx
> +        <PlaceHolder
<img width="313" alt="스크린샷 2023-10-22 오후 12 07 47" src="https://github.com/taeo-sprint16/frontend/assets/77668478/5e5a6c9e-1007-42f3-b625-dcbb14cbd9c9">

textarea heigth가 size가 아래로 늘어나지않아서 상단 요소가 밀리는 부분이 있는거 같아요! 확인부탁드릴게요!

2023-10-22 09:08 UTC, brother1-4752 approved these changes
textarea 높이 자동조절은 답변 작성 만들때 고려 안했는데, 저도 시간되면 적용해야겠네요!! 수고하셨어요!

2023-10-22 13:42 UTC, HA-SEUNG-JEONG commented on src/components/NickName.tsx
>  const StyledQuestionContainer = styled.div`
완료했습니다!

2023-10-22 13:51 UTC, HA-SEUNG-JEONG commented
media query로 반응형 달아놓긴 했는데 수정해야 할 부분 있으면 바로 알려주세요!

2023-10-22 14:27 UTC, brother1-4752 approved these changes
반응형 넘 어렵네요.. 반응형 디자인, 질문 작성 화면 구현하느라 수고하셨어요👍

2023-10-22 15:09 UTC, bbung95 requested changes
리뷰 확인 부탁드립니다!

2023-10-22 15:09 UTC, bbung95 commented on src/components/NickName.tsx
> +  align-items: center;
![스크린샷 2023-10-23 오전 12 00 21](https://github.com/taeo-sprint16/frontend/assets/77668478/fb49af66-3ed0-4dac-8395-a0a5867c025f)

Title 부분이 왼쪽 정렬이 안되있는거 같아요!

const Wrapper = styled.div`
align-items: center;
`
부분 수정하면 좋을거같습니다!

2023-10-22 15:09 UTC, bbung95 commented on src/components/WriteQuestion.tsx
> +      )}
![스크린샷 2023-10-23 오전 12 05 53](https://github.com/taeo-sprint16/frontend/assets/77668478/525d22ed-913d-4e5f-917f-15a6d9386d5b)

하단에 질문 작성 완료 버튼이 없는거 같아요!! 추가 부탁드릴게요!

2023-10-22 15:18 UTC, HA-SEUNG-JEONG commented on src/components/WriteQuestion.tsx
> +      )}
<img width="201" alt="image" src="https://github.com/taeo-sprint16/frontend/assets/88266129/6ef95321-535e-4b5d-9a30-51739b28bc7d">

여기서 '완료'를 클릭하면 '질문 작성 완료' 버튼이 나오는데 다시 확인부탁드립니다!

2023-10-22 15:40 UTC, bbung95 commented on src/components/NickName.tsx
> +  }
버튼이 양쪽 24px 여백을 제외하고 채워져야합니다!

2023-10-23 01:07 UTC, HA-SEUNG-JEONG commented on src/components/NickName.tsx
> +  }
완료했습니다!

2023-10-23 09:11 UTC, bbung95 approved these changes

2023-10-23 10:32 UTC, merged